/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ERB03.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('objects/ERB03/ERB03.gltf')
  return (
    <group {...props} dispose={null}>

      <group position={[0, -0.15, 0]} scale={[0.604, 0.058, 0.604]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('objects/ERB03/ERB03.gltf')
