/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RM01.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('objects/RM01/RM01.gltf')
  return (
    <group {...props} dispose={null}>
      
      <group rotation={[29.84, 3.13, 2]} scale={2.5} position={[0, 0.65, 0]}>
        
      <mesh geometry={nodes.RM01_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.RM01_2.geometry} material={materials['Material.012']} />
      </group>

    </group>
  )
}

useGLTF.preload('objects/RM01/RM01.gltf')
