/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 OBJ_6.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('objects/OBJ_6/OBJ_6.gltf')
  return (
    <group {...props} dispose={null}>
      <group  rotation={[-1, 1.6, -0.5]} >
        <mesh geometry={nodes.cap_6002.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.cap_6002_1.geometry} material={materials['cap_6.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('objects/OBJ_6/OBJ_6.gltf')
