/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 OBJ_6.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('objects/OBJ_6/OBJ_6.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.01, 0.294, -0.009]} scale={[0.604, 0.058, 0.604]} />
      <mesh geometry={nodes.cap_6.geometry} material={materials.cap_6} position={[0.103, 0.149, 7.186]} rotation={[-Math.PI / 2, -1.464, -Math.PI]} scale={2.496} />
    </group>
  )
}

useGLTF.preload('objects/OBJ_6/OBJ_6.gltf')
