/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ABR02.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('objects/ABR02/ABR02.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('objects/ABR02/ABR02.gltf')
